### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ghost** [LevitatingBusinessMan/micro-discord#1]
it just doesn't work. the presence doesn't show up

**Comment by LevitatingBusinessMan** [comment]
This project is still very experimental.

To get it to work, you got to start a special daemon I wrote: `./micro_rpc -d`.

After that it should work, but there's still no way for the daemon to know when you quit micro so it keeps displaying the status on Discord until you quit the daemon.

**Comment by LevitatingBusinessMan** [comment]
It's possibly not starting the `micro_rpc` daemon.

You can try launching it yourself with `./micro_rpc -d` and see if it reports anything when you open a file in micro.

In any case this software is still extremely experimental, and buggy.
